### PR TITLE
Analyse dependencies for Java 9 modules

### PR DESCRIPTION
**Pull request by neomatrix369**
Add a new task called 'jdeps' to help generate verbose dependencies information on the modules and packages used by the project and its dependencies

Assists in investigating issue https://github.com/julianghionoiu/tdl-lord-of-runners/pull/8

### CODE REVIEW

**Review by julianghionoiu — APPROVED** [review]

**Comment by julianghionoiu** [comment]
Looks good, but for some reason the build failed on the CI.

**Comment by neomatrix369** [comment]
The https://app.codeship.com/home does not list failed entry, it could have failed due to the same reason the IDE was complaining - unable to resolve `ro.ghionoiu:dev-screen-record:0.0.6`, although I don't see the logs so can't tell. Works fine on local machine so much be something wrong elsewhere.

**Comment by julianghionoiu** [comment]
I have given you access to Codeship, the output is confusing, looks like it gets stuck in an infinite loop when it tries to resolve jaxb-api-2.2.11.jar

**Comment by neomatrix369** [comment]
Unfortunately gradle controls the output and not sure if there is a way to simplify the output:
```
./gradlew clean build -i
```
The above command prints info messages, for build message I would suggest to switch to debug mode.

**Comment by neomatrix369** [comment]
I noticed the reason for the failure, amend the .gradle config

**Comment by neomatrix369** [comment]
Looking at the output in the CodeShip console it appears its not indenting or formatting the gradle output correctly like it would on local machine CLI - worth informing Codeship

**Review by julianghionoiu — APPROVED** [review]

**Pull request merged**
